### ISSUE TITLE
Changing license

### ISSUE THREAD

**Issue by dan-blanchard** [chardet/chardet#36]
This feels strange to be posing as a question, since I'm one of the co-maintainers, but @sigmavirus24 and @erikrose, do you know if it's okay/legal for us to change the license of chardet?  Because it was started by Mark Pilgrim I feel like it's kind of a nebulous question, because he's not someone you can just email, and he has nothing to do with development anymore.  I would really like to change the license to at least be MPL, since that's what the C++ version is, and our setup currently mirrors that code pretty closely. 

I'm not a fan of the LGPL and feel weird having a project I work on use it.

**Comment by johnthagen** [comment]
FWIW, https://github.com/Ousret/charset_normalizer seems to be an alternative package that is MIT licensed.

**Comment by johnthagen** [comment]
@dan-blanchard I see you have been contributing to `chardet` recently. Any chance this issue could be revisited?

LGPL makes it challenging for including `chardet` (or any of the many packages that transitively depend on `chardet` such as `requests`)  inside of a binary due to the restriction that users need to be able to have the ability to swap out the LGPL library for another of their choosing, something infeasible for a binary distribution.

This affects users of [Pyinstaller](https://www.pyinstaller.org/), [Nuitka](https://nuitka.net/), [PyOxdizer](https://pyoxidizer.readthedocs.io/en/stable/), etc. that want to package their Python code and dependencies into a stand-alone binary.

**Comment by dan-blanchard** [comment]
Unfortunately, because the code that chardet was originally based on was LGPL, we don't really have a way to relicense it. Believe me, if we could, I would. There was talk of chardet being added to the standard library, and that was deemed impossible because of being unable to change the license.

**Comment by BrettMoan** [comment]
@dan-blanchard  any chance you could maybe talk to the maintainers of `requests` to get off of `chardet` given the inability to change the license? 

I know its odd someone, to ask others to _not_ use their code, but such a restriction of `chardet` prevents development of closed source using one of the most downloaded packages on the pypi. `requests` and even the python documentation on `urllib.requests` seem to be overlooking this problem that the LGL introduces. 

Those who work with license scanning software, to ensure their code doesn't contain copy-left linking will eventually see `chardet` and be confused given that their code doesn't knowingly contain that and will end up down a familiar rabbit hole for many, where they use `requests` which then leads to the install of `chardet` all because they followed the plethora of examples to use `requests` including the quote from `urllib.request` documentation itself suggesting it.


> See also The Requests package is recommended for a higher-level HTTP client interface.
> ---  https://docs.python.org/3/library/urllib.request.html#module-urllib.request:

Given than that its license prevents it from being included in the standard library, it seems odd that the the standard library documentation is actually _recommending_ a package that has it as a dependency.

**Comment by sigmavirus24** [comment]
Hi, requests maintainer here. We're not dropping the dependency any time soon. @dan-blanchard you can say we've talked now

**Comment by sigmavirus24** [comment]
Also, I'm aware of many enterprise companies using requests + chardet with license scanning software. LGPL is a gray area in Python and not nearly as infections as AGPL or the non-open-source licenses like SSPL.

**Comment by johnthagen** [comment]
I'm curious if there anything in particular about [`charset_normalizer`](https://github.com/Ousret/charset_normalizer) that makes it unsuitable compared to `chardet`? It advertises itself as an MIT-licensed alternative. Could migration to that be a solution?

**Comment by sigmavirus24** [comment]
We (the maintainers) don't have the time to make such a migration with confidence or without the risk of introducing bugs. Regardless, `alternative` doesn't mean drop-in replacement that doesn't regress behaviour for Requests. Conversations like this tend to take up more of our time given how limited our time is to do work on Requests. This precludes us from exploring other options, making improvements, or doing anything except the bare minimum (researching/fixing security bugs, etc.)

**Comment by BrettMoan** [comment]
@sigmavirus24 for the maintainers of `requests` is it a "wont fix" or a "don't have time to fix"?

Curious if the maintainers are opposed to merge requests that attempt to replace `chardet`, I've seen every conversation regarding this "closed" with the conversation implying a "won't fix".

If its a "don't have time to fix" then people who are invested in this as an issue could attempt to resolve it.

**Comment by sigmavirus24** [comment]
It's both really

**Comment by sheepdestroyer** [comment]
> I know its odd someone, to ask others to _not_ use their code, but such a restriction of `chardet` **prevents development of closed source** using one of the most downloaded packages on the pypi.

"**_prevents development of closed source_**" :  Good, that's LGPL's intent. 
Tying to change this would be a morally wrong dick move aimed at maiming user freedoms.
