### ISSUE TITLE
CP949 detected for what used to be ASCII

### ISSUE THREAD

**Issue by deanmalmgren** [chardet/chardet#98]
Thank you for putting this package together and going through the hassle of merging these versions. Sounds like you've been busy!

I maintain [textract](https://github.com/deanmalmgren/textract) and we've recently had a few issues where the encoding detection is not working as well as it once did (e.g. https://github.com/deanmalmgren/textract/issues/107, https://github.com/deanmalmgren/textract/issues/133, and https://github.com/deanmalmgren/textract/issues/135) . When I revert back to version `2.1.1`, I am successfully able to detect that the file mentioned in https://github.com/deanmalmgren/textract/issues/107 is ASCII encoded. Later versions describe it as CP949, which causes problems for textract.

I would be happy to help address this issue. I am not familiar with the chardet codebase, so if you could point me in the right direction, that would be great. In the meantime, I can pin the version to chardet 2.1.1 which should hopefully resolve the issue in the interim.

**Comment by dan-blanchard** [comment]
I appreciate the offer to help. I've slowly but steadily been making progress on a large overhaul of our single byte character encoding detection code. I'm retraining our language models, adding support for way more languages and encodings, and adding some performance boosts. Of course, I keep tweaking the model training code because the models aren't quite how I'd like them, which is why this is taking me so long. I'm only able to dedicate a couple days per month to chardet right now, but even with that I think I'm very close to having a PR ready to go for these changes.

**Comment by deanmalmgren** [comment]
Thanks for making progress on the overhaul of the byte detection algorithm. I understand the challenge of doing a big open source overhaul like that and I look forward to seeing the outcome! I had seen you and others allude to this in other issues and I'd be happy to provide some test cases of that would be helpful.

In the meantime, I'm going to leave this open until the encoding issues that we've been having with textract are resolved.

It appears  https://github.com/deanmalmgren/textract/issues/107 was not entirely resolved by rolling back to 2.1.1. We upgraded textract to support py3 a while back and as a result we will need to use chardet 2.2+ going forward (thanks for incorporating that change!).

**Comment by dan-blanchard** [comment]
Just checked the file in question with the 3.0 release and it reports ASCII again.

**Comment by deanmalmgren** [comment]
fantastic! thanks @dan-blanchard :)
